version: "3.9"

services:
  app:
    container_name: app
    build: app
    restart: always
    tty: true
    volumes:
      - ./app:/app
    environment:
      - HATENA_CONSUMER_KEY=${HATENA_CONSUMER_KEY}
      - HATENA_CONSUMER_SECRET=${HATENA_CONSUMER_SECRET}
      - HATENA_ACCESS_TOKEN=${HATENA_ACCESS_TOKEN}
      - HATENA_ACCESS_TOKEN_SECRET=${HATENA_ACCESS_TOKEN_SECRET}
      - HATENA_RK=${HATENA_RK}
      - HATENA_RKS=${HATENA_RKS}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
